name: Installers

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  version:
    name: Jammy Mainline
    runs-on: ubuntu-latest
    steps:
      - name: Import GPG key
        run: |
          cat <(echo -e "${{ secrets.GPG_LAUNCHPAD }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: Get Tag
        id: tag
        run: |
          curl -o Makefile https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/plain/Makefile?h=linux-rolling-stable
          echo "KERNEL_TAG=$(head -4 Makefile | tail -3 | sed 's/[A-Z =]//g' | sed ':a;N;$!ba;s/\n/\./g')" >> "$GITHUB_OUTPUT"
          rm Makefile

      - name: Checkout
        run: |
          git clone \
            --depth 1 \
            --branch "cod/mainline/v${{ steps.tag.outputs.KERNEL_TAG }}" \
            "https://git.launchpad.net/~ubuntu-kernel-test/ubuntu/+source/linux/+git/mainline-crack" \
            "linux-${{ steps.tag.outputs.KERNEL_TAG }}"

      - name: Build dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get -y install dput-ng python3-paramiko devscripts debhelper

      - name: Build
        env:
          DEBEMAIL: "ingo@jitsi.org"
          DEBFULLNAME: "Ingo Bauersachs"
        run: |
          cd "linux-${{ steps.tag.outputs.KERNEL_TAG }}"
          dch -D jammy --newversion "$(head -1 debian.master/changelog | grep -Eoh '${{ steps.tag.outputs.KERNEL_TAG }}-[0-9]+').$(date +%Y%m%d%H%M)" --changelog debian.master/changelog "Fix invoking zstd with no files" || true
          sed -i "s/gcc-13/gcc-11/" debian/rules.d/0-common-vars.mk
          fakeroot debian/rules clean
          # fix zstd compression command
          sed -i "s/xargs/xargs -r/" debian/rules.d/2-binary-arch.mk
          dpkg-buildpackage -d -S --sign-key=FA64266C2979E1702BCA904EC532E6511AA8714C

      - name: Upload as artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: files
          path: "linux_*"

      - name: Upload to PPA
        run: |
          dput ppa:ibauersachs/mainline-kernel linux_*.changes
